"""Neyman-Scott cluster process in a square."""

import numpy as np


def cluster_square(
    cls,
    intensity=(10, 10),
    cluster=None,
    limit=1,
    seed=None,
):
    """
    Generates points according to a Neyman-Scott cluster process in a square region.

    A Neyman-Scott process is a type of cluster point process where "parent" points
    are first generated by a Poisson process. Then, for each parent, a random
    number of "daughter" points are scattered around it according to some
    distribution. This method implements two types of daughter point distributions:
    Matern and Thomas.

    The generation process involves:
    1.  **Parent Point Generation**:
        *   Parent points are generated from a homogeneous Poisson point
            process with intensity `intensity[0]`.
        *   This generation occurs in an "extended window" larger than the final
            simulation window `(0, limit) x (0, limit)`. The extension size depends
            on the cluster type (`radius` for Matern, `5*sigma` for Thomas) to
            mitigate edge effects where clusters centered near the boundary might
            incorrectly have fewer points within the final window.

    2.  **Daughter Point Generation (Clustering)**:
        *   For each parent point, a number of daughter points is drawn from a
            Poisson distribution with mean `intensity[1]`.
        *   The spatial distribution of these daughter points around their parent
            depends on the `cluster["name"]`:
            *   **"Matern"**: Daughter points are uniformly distributed
                within a disk of `radius = cluster["param"]` centered at
                the parent point. This is achieved by generating points in
                polar coordinates (rho, theta) where theta is U(0, 2*pi)
                and rho is `radius * sqrt(U(0,1))`.
            *   **"Thomas"**: Daughter points are distributed according to
                an isotropic bivariate Gaussian (Normal) distribution
                centered at the parent point, with standard deviation
                `sigma = cluster["param"]` for both x and y directions.

    3.  **Thinning to Final Window**:
        *   All generated daughter points are considered. Only those
            points that fall within the original simulation window defined
            by `(0, limit) x (0, limit)`
            are retained in the final output.

    Parameters:
    ----------
    intensity : tuple of float
        A tuple `(intensity_parent, intensity_daughter)`.
        `intensity[0]` is the intensity of the parent Poisson process.
        `intensity[1]` is the mean number of daughter points per parent.
    cluster : dict
        A dictionary specifying the cluster generation mechanism.
        It must contain:
        `"name"`: str, either "Matern" or "Thomas".
        `"param"`: float, the parameter for the chosen mechanism
                   (disk radius for Matern, standard deviation sigma for Thomas).
    limit : float
        The side length of the square simulation window `(0, limit) x (0, limit)`.
        Must be a positive value.
    seed : int, optional
        A seed for the random number generator to ensure reproducibility.
        If None, the RNG is initialized without a specific seed. Defaults to None.
    """
    if cluster is None:
        cluster = {"name": "Matern", "param": 0.1}
    rng = np.random.default_rng(seed=seed)
    limits = ((0, limit), (0, limit))
    # intensity[0] - density of parent Poisson point process
    # indensity[1] - mean number of points in each cluster
    # Extended simulation window parameters
    xmin, xmax = limits[0]
    ymin, ymax = limits[1]
    if cluster["name"] == "Matern":
        radius = cluster["param"]
    elif cluster["name"] == "Thomas":
        radius = 5 * cluster["param"]
    xmin_ext = xmin - radius
    xmax_ext = xmax + radius
    ymin_ext = ymin - radius
    ymax_ext = ymax + radius
    xdelta = xmax_ext - xmin_ext
    ydelta = ymax_ext - ymin_ext
    area = xdelta * ydelta
    # Simulated Poisson points process for the parents
    n_points_parent = rng.poisson(area * intensity[0])
    x_parent = xmin_ext + xdelta * rng.uniform(0, 1, n_points_parent)
    y_parent = ymin_ext + ydelta * rng.uniform(0, 1, n_points_parent)
    # Simulate Poisson point process for the daughters
    n_points_daughter = rng.poisson(intensity[1], size=n_points_parent)
    n_points = sum(n_points_daughter)
    if cluster["name"] == "Matern":
        # Generate the (relative) locations in polar coordinates
        theta = 2 * np.pi * rng.uniform(0, 1, n_points)
        rho = radius * np.sqrt(rng.uniform(0, 1, n_points))
        # Convert from polar to Cartesian coordinates
        x_aux = rho * np.cos(theta)
        y_aux = rho * np.sin(theta)
    elif cluster["name"] == "Thomas":
        # Generate the (relative) locations in Cartesian coordinates
        x_aux = rng.normal(0, cluster["param"], n_points)
        y_aux = rng.normal(0, cluster["param"], n_points)
    # replicate parent points (ie centres of disks/clusters)
    x = np.repeat(x_parent, n_points_daughter)
    y = np.repeat(y_parent, n_points_daughter)
    x = x + x_aux
    y = y + y_aux
    # thin points if outside the simulation window
    inside = (x >= xmin) & (x <= xmax) & (y >= ymin) & (y <= ymax)
    # retain points inside simulation window
    x = x[inside]
    y = y[inside]
    points = np.stack((x, y), axis=1)
    return cls(points, seed=rng.integers(low=0, high=2**32 - 1))
